/*
 * generated by Xtext 2.9.1
 */
package info.scce.testdsl.tests

import com.google.inject.Inject
import info.scce.testdsl.testDSL.prog
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(TestDSLInjectorProvider)
class TestDSLParsingTest{

	@Inject
	ParseHelper<prog> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
