/*
 * generated by Xtext 2.9.1
 */
package info.scce.testdsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TestDSLStandaloneSetup extends TestDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new TestDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
