/*
 * generated by Xtext 2.9.1
 */
package info.scce.testdsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TestDSLRuntimeModule extends AbstractTestDSLRuntimeModule {
}
